#################################
#          Animations
#################################
fading = true
fade-in-step = 1
fade-out-step = 1
fade-delta = 0

#################################
#          Transparency
#################################
inactive-opacity = 0.90;    # Transparency of inactive windows
active-opacity = 1.0;
frame-opacity = 0.9;
inactive-opacity-override = false;
opacity-rule = [
  "70:class_g = 'Polybar'",
  "90:class_g = 'kitty'",
  "90:class_g = 'term'",
  "90:class_g = 'nvim'",
  "90:class_g = 'nvim-workflow'",
  "90:class_g = 'editor'",
  "90:class_g = 'yazi'",
  "80:class_g = 'Rofi'",
  "90:class_g = 'Code'"
];

#################################
#          Shadows
#################################
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.75;
# Don’t add shadow to these:
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'",
  "class_g = 'i3-frame'",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#          Corners
#################################
corner-radius = 12;
round-borders = 1;
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'i3-frame'",
  "window_type = 'dock'"
];

#################################
#          Blur
#################################
blur-method = "dual_kawase";
blur-strength = 5;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
blur-kern = "3x3box";

#################################
#          General
#################################
backend = "glx";
vsync = true;
unredir-if-possible = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
inactive-dim = 0.4;
focus-exclude = [ "class_g = 'Rofi'" ];
