include pink_theme.conf
font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Bold
italic_font      JetBrainsMono Nerd Font Mono Italic
bold_italic_font JetBrainsMono Nerd Font Mono Bold Italic
bold_font        auto
italic_font      auto
bold_italic_font auto
enable_audio_bell no
font_size 12.0
window_padding_width 5
cursor_shape block
confirm_os_window_close 0
wheel_scroll_min_lines 1
wheel_scroll_multiplier 1.0

map shift+up scroll_line_up
map shift+down scroll_line_down

map ctrl+backspace send_text all \x17

# Enable selection with shift + arrows
select_by_word_characters @-./_~?&=%+#

map ctrl+minus change_font_size all -1.0

#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0

allow_remote_control yes

# Vim Scrollback
map ctrl+h launch --stdin-source=@screen_scrollback --type=overlay nvim -n -u ~/.config/kitty/scrollback.vim -i NONE + -

