[colors]
alert          = #FF4F81
background     = #1E1B24  
background-alt = #2A2430 
disabled       = #7D5C6E
foreground     = #EADDE1
primary        = #FF79C6
secondary      = #FFB3D9
battery-full   = #4CAF50

[settings]
pseudo-transparency = true
screenchange-reload = true

[bar/example]
monitor = ${env:MONITOR:}
width = 100%
height = 22pt
radius = 7

background = ${colors.background}
foreground = ${colors.foreground}

border-color = #00000000
border-size = 4pt

line-size = 3pt
padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMono Nerd Font Mono:size=10;3   
font-1 = JetBrainsMono Nerd Font Mono:size=15;0  

modules-left = i3 playerctl
modules-center = date
modules-right = pulseaudio memory cpu cpu-temp wireless-network backlight battery

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/battery]
type = internal/battery

full-at = 99
low-at = 20

battery = BAT0
adapter = ADP1
poll-interval = 5

time-format = %H:%M

format-charging = <animation-charging> <label-charging>

format-discharging = <animation-discharging> <label-discharging>

label-charging = %percentage%%

label-discharging = %percentage%%
label-full =  100%
label-full-foreground = ${colors.battery-full}
label-low = BATTERY LOW
label-low-foreground = ${colors.alert}

; Only applies if <animation-charging> is used
animation-charging-0 = "󱐋 "
animation-charging-1 = "󱐋 "
animation-charging-2 = "󱐋 "
animation-charging-3 = "󱐋 "
animation-charging-4 = "󱐋 "
; Framerate in milliseconds
animation-charging-framerate = 750
animation-charging-foreground = ${colors.primary}

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500
animation-discharging-foreground = ${colors.primary}

[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
poll-interval = 0
enable-scroll = true
scroll-interval = 10
format-prefix = " "
format-prefix-foreground = ${colors.primary}
format = <label>
label = %percentage%%

[module/i3]
type = internal/i3
pin-workspaces = true
enable-click = true
enable-scroll = false
strip-wsnumbers = false   

ws-icon-0 = web;󰖟
ws-icon-1 = editor;
ws-icon-2 = term;
ws-icon-3 = exp;
ws-icon-4 = spotify;
ws-icon-5 = slack;
ws-icon-6 = whatsapp;
ws-icon-7 = ticktick;
ws-icon-8 = chatgpt;
ws-icon-9 = git;󰊢
ws-icon-10 = zathura;󰈦 
ws-icon-11 = mail;
ws-icon-12 = meet;
ws-icon-13 = work;
ws-icon-14 = obsidian;
ws-icon-default = 

label-focused   = %{T1}%icon%%{T-}
label-unfocused = %{T1}%icon%%{T-}
label-visible   = %{T1}%icon%%{T-}
label-urgent    = %{T1}%icon%%{T-}
label-empty     = %{T1}%icon%%{T-}

label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background-alt}
label-focused-underline  = ${colors.primary}
label-focused-padding    = 1

label-unfocused-padding  = 1

label-visible-foreground = ${colors.foreground}
label-visible-padding    = 1

label-urgent-background  = ${colors.alert}
label-urgent-foreground  = ${colors.background}
label-urgent-padding     = 1

label-empty-foreground   = ${colors.disabled}
label-empty-padding      = 1

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/cpu-temp]
type = internal/temperature
interval = 2
zone-type = ${env:POLYBAR_CPU_ZONE_TYPE:x86_pkg_temp}
thermal-zone = ${env:POLYBAR_CPU_THERMAL_ZONE:7}
warn-temperature = 80
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %temperature-c%
format-warn = <label-warn>
label-warn = %temperature-c%
label-warn-foreground = ${colors.alert}

[module/date]
type = internal/date
interval = 1

date = %a %H:%M
date-alt = %a %Y-%m-%d %H:%M:%S

format-prefix = " "
format-prefix-foreground = ${colors.primary}

label = %date%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %gb_used:2%

[module/playerctl]
type = custom/script
exec = ~/.config/polybar/scripts/playerctl.sh
tail = true

; clicks / scroll
click-left  = playerctl play-pause
click-right = playerctl stop
scroll-up   = playerctl next
scroll-down = playerctl previous

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
ramp-volume-foreground = ${colors.primary}

label-volume = %percentage%%

label-muted = " muted"
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/wireless-network]
type = internal/network
interface = wlo1

format-connected = <ramp-signal> <label-connected>

format-disconnected = <label-disconnected>

label-connected = %essid% 

label-disconnected = not connected
label-disconnected-foreground = #66ffff

ramp-signal-0 = 󰤫
ramp-signal-1 = 󰤯
ramp-signal-2 = 󰤟
ramp-signal-3 = 󰤢
ramp-signal-4 = 󰤥
ramp-signal-5 = 󰤨
ramp-signal-foreground = ${colors.primary}
