
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

decoration {
	dim_inactive = true
	dim_strength = 0.23
}

exec-once = wlsunset -t 4500 -l -31.4 -L -64.1 # dim screen at sunset
exec-once = kdeconnect-cli -n Galaxy\ S20 # connect to phone through kdeconnect
exec-once = ~/scripts/capslock_notifier.sh

# Automatically open apps in their own workspace
windowrulev2 = workspace special:spotify, class:^(vivaldi-pjibgclleladliembfgfagdaldikeohf-Default) # Spotify App
windowrulev2 = workspace special:whatsapp, class:^(vivaldi-hnpfjngllnobngcgfapefoaidbinmjnm-Default) # WhatsApp App
windowrulev2 = workspace special:discord, class:^(vivaldi-mfhpbolkhgobaabcbabdlnhidbjpoogc-Default) # Discord App
windowrulev2 = workspace special:ticktick, class:^(vivaldi-cfammbeebmjdpoppachopcohfchgjapd-Default) # TickTick App
windowrulev2 = workspace special, class:^(todui)$

exec-once = hyprctl dispatch exec [ workspace special:spotify silent ] "/opt/vivaldi/vivaldi --profile-directory=Default --app-id=pjibgclleladliembfgfagdaldikeohf" && sleep 1 && hyprctl dispatch exec [ workspace special:whatsapp silent ] "/opt/vivaldi/vivaldi --profile-directory=Default --app-id=hnpfjngllnobngcgfapefoaidbinmjnm" && sleep 1 && hyprctl dispatch exec [ workspace special:discord silent ] "/opt/vivaldi/vivaldi --profile-directory=Default --app-id=mfhpbolkhgobaabcbabdlnhidbjpoogc" && sleep 1 && hyprctl dispatch exec [ workspace special:ticktick silent ] "/opt/vivaldi/vivaldi --profile-directory=Default --app-id=cfammbeebmjdpoppachopcohfchgjapd" && ~/.config/hypr/hide_scratchpads_script.sh && hyprctl dispatch workspace 2 && hyprctl dispatch exec neovide && hyprctl dispatch workspace 3 && hyprctl dispatch exec kitty && hyprctl dispatch workspace 1 && hyprctl dispatch exec vivaldi 
