-- Editable application catalog. See hyde/HYPRLAND.md for examples and fields.
-- Array order controls startup: sequential apps, parallel apps, then last apps.
-- Keys are combined with mainMod. Omit startup to keep an app out of autostart.
-- Shared appearance values; an individual entry can use its own opacity string.
local opaque = "1 override 1 override 1 override"
local terminalOpacity = "0.95 override 0.95 override 1 override"
local utilityOpacity = "0.8 override 0.8 override 1 override"

return {
	{
		id = "spotify",
		class_prefix = "vivaldi-spotify.com",
		runtime_suffix = "__",
		command = "/opt/vivaldi/vivaldi --app=https://spotify.com",
		workspace = "special:spotify",
		key = "S",
		startup = "sequential",
		action = "toggleSpotify",
		focus_class = "vivaldi-spotify.com__-Default",
		search = { mods = "CTRL", key = "code:45" },
	},
	{
		id = "whatsapp",
		class_prefix = "vivaldi-web.whatsapp.com",
		match = { class = [[^(vivaldi-web.whatsapp\.com.*)$]] },
		runtime_suffix = "__",
		command = "/opt/vivaldi/vivaldi --app=https://web.whatsapp.com",
		workspace = "special:whatsapp",
		key = "W",
		startup = "sequential",
		properties = { no_screen_share = true },
		search = { mods = "ALT", key = "code:45", class = "vivaldi-web.whatsapp.com__-Default" },
	},
	{
		id = "ticktick",
		class_prefix = "vivaldi-ticktick.com",
		runtime_suffix = "__",
		command = "/opt/vivaldi/vivaldi --app=https://ticktick.com",
		workspace = "special:ticktick",
		key = "T",
		startup = "sequential",
		properties = { no_screen_share = true },
		search = { mods = "CTRL", key = "code:45" },
	},
	{
		id = "chatgpt",
		class_prefix = "vivaldi-chatgpt.com",
		runtime_suffix = "__",
		command = "/opt/vivaldi/vivaldi --app=https://chatgpt.com",
		workspace = "special:chatgpt",
		key = "TAB",
		startup = "sequential",
		properties = { group = "set invade always" },
		search = { mods = "CTRL", key = "code:45" },
	},
	{
		id = "nvim",
		class = "nvim",
		command = "kitty --class nvim --title nvim nvim",
		workspace = "2",
		startup = "parallel",
		properties = { opacity = terminalOpacity, group = "set invade always" },
	},
	{
		id = "term",
		class = "term",
		command = "kitty --class term",
		workspace = "3",
		workspace_match = { initial_title = "^(kitty)$" },
		startup = "parallel",
		properties = { opacity = terminalOpacity },
	},
	{
		id = "yazi",
		class = "yazi",
		command = "kitty --class yazi --title yazi yazi",
		workspace = "4",
		startup = "parallel",
		properties = { opacity = terminalOpacity },
	},
	{ id = "browser", class = "vivaldi-stable", command = "vivaldi", startup = "last" },
	{
		id = "terminal",
		class = "kitty",
		command = "kitty",
		key = "SPACE",
		properties = { opacity = "0.92 override 0.92 override 1 override" },
	},
	{
		id = "discord",
		class_prefix = "vivaldi-discord.com",
		runtime_suffix = "__",
		workspace = "special:discord",
		key = "D",
		search = { mods = "CTRL", key = "code:45" },
	},
	{
		id = "pdf",
		match = { class = "^(org.pwmt.zathura)$" },
		workspace = "special:pdf",
		key = "F",
		properties = { group = "set invade always" },
	},
	{ id = "obs", match = { class = "^(com.obsproject.Studio)$" }, workspace = "special:obs", key = "R" },
	{
		id = "github",
		class_prefix = "vivaldi-github.com",
		workspace = "special:github",
		key = "G",
		properties = { group = "set invade always" },
	},
	{ id = "obsidian", class = "obsidian", workspace = "special:obsidian", key = "K" },
	{ id = "meet", class_prefix = "vivaldi-meet.google.com", workspace = "special:meet", key = "MINUS" },
	{
		id = "mail",
		match = { class = [[^(vivaldi-mail\.google\.com.*|vivaldi-outlook\.live\.com.*)$]] },
		workspace = "special:mail",
		key = "M",
		properties = { group = "set invade always", no_screen_share = true },
	},
	{
		id = "lyrics",
		class = "lyrics",
		command = "kitty --class lyrics -o font_size=15 -o background_opacity=0.7 -e sptlrx -p mpris",
		key = "SHIFT + S",
		action = "toggleLyrics",
		bind_options = { description = "$d lyrics window" },
		properties = {
			float = true,
			pin = true,
			no_initial_focus = true,
			no_dim = true,
			size = "443 227",
			move = "monitor_w-window_w-8 monitor_h-window_h-8",
			opacity = opaque,
		},
	},
	{
		id = "notebooklm",
		class_prefix = "vivaldi-notebooklm.google.com",
		workspace = "special:chatgpt",
		properties = { group = "set invade always" },
	},
	{
		id = "youtube",
		class_prefix = "vivaldi-youtube.com",
		workspace = "5",
		properties = { group = "set lock invade always" },
	},
	{
		id = "neovide",
		class = "neovide",
		workspace = "2",
		properties = { opacity = terminalOpacity, group = "set invade always" },
	},
	-- Appearance-only entries. These do not launch apps or register shortcuts.
	{ id = "satty", match = { class = "^(com.gabm.satty)$" }, properties = { float = true } },
	{ id = "firefox", class = "firefox", properties = { opacity = opaque } },
	{ id = "brave", class = "Brave-browser", properties = { opacity = opaque } },
	{ id = "code-oss", class = "code-oss", properties = { opacity = opaque } },
	{ id = "code", match = { class = "^([Cc]ode)$" }, properties = { opacity = opaque } },
	{ id = "code-lower", class = "code", properties = { opacity = opaque } },
	{ id = "code-url", class = "code-url-handler", properties = { opacity = opaque } },
	{ id = "code-insiders-url", class = "code-insiders-url-handler", properties = { opacity = opaque } },
	{ id = "zed", match = { class = "^(dev.zed.Zed)$" }, properties = { opacity = terminalOpacity } },
	{ id = "dolphin", match = { class = "^(org.kde.dolphin)$" }, properties = { opacity = utilityOpacity } },
	{ id = "ark", match = { class = "^(org.kde.ark)$" }, properties = { opacity = opaque } },
	{ id = "nwg-look", class = "nwg-look", properties = { opacity = opaque } },
	{ id = "qt5ct", class = "qt5ct", properties = { opacity = opaque } },
	{ id = "qt6ct", class = "qt6ct", properties = { opacity = opaque } },
	{ id = "kvantum", class = "kvantummanager", properties = { opacity = opaque } },
	{ id = "pavucontrol", match = { class = "^(org.pulseaudio.pavucontrol)$" }, properties = { opacity = utilityOpacity } },
	{ id = "blueman", class = "blueman-manager", properties = { opacity = utilityOpacity } },
	{ id = "nm-applet", class = "nm-applet", properties = { opacity = utilityOpacity } },
	{ id = "nm-editor", class = "nm-connection-editor", properties = { opacity = utilityOpacity } },
	{ id = "kde-polkit", match = { class = "^(org.kde.polkit-kde-authentication-agent-1)$" }, properties = { opacity = opaque } },
	{ id = "gnome-polkit", class = "polkit-gnome-authentication-agent-1", properties = { opacity = opaque } },
	{ id = "portal-gtk", match = { class = "^(org.freedesktop.impl.portal.desktop.gtk)$" }, properties = { opacity = opaque } },
	{ id = "portal-hyprland", match = { class = "^(org.freedesktop.impl.portal.desktop.hyprland)$" }, properties = { opacity = opaque } },
	{
		id = "yazi-selector",
		class = "yazi-selector",
		properties = {
			opacity = opaque,
			float = true,
			move = "monitor_w*0.5-window_w*0.5 monitor_h*0.5-window_h*0.5",
		},
	},
	{ id = "steam", match = { class = "^([Ss]team)$" }, properties = { opacity = opaque } },
	{ id = "steamwebhelper", class = "steamwebhelper", properties = { opacity = opaque } },
	{ id = "spotify-native", match = { class = "^([Ss]potify)$" }, properties = { opacity = opaque } },
	{ id = "spotify-free", match = { initial_title = "^(Spotify Free)$" }, properties = { opacity = opaque } },
	{ id = "spotify-premium", match = { initial_title = "^(Spotify Premium)$" }, properties = { opacity = opaque } },
}
