player: mpris
ignoreErrors: true
timerInterval: 200
updateInterval: 500
style:
  hAlignment: center
  before:
    background: ""
    foreground: "#57678F"
    bold: false
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: false
  current:
    background: ""
    foreground: "#E2AAF0"
    bold: true
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: "#9AAFE6"
    bold: false
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: true
pipe:
  length: 0
  overflow: word
mpd:
  address: 127.0.0.1:6600
  password: ""
mopidy:
  address: 127.0.0.1:6680
mpris:
  players: []
browser:
  port: 8974
local:
  folder: ""
