return {
	"NeogitOrg/neogit",
	dependencies = {
		"nvim-lua/plenary.nvim", -- required
		"sindrets/diffview.nvim", -- optional - Diff integration

		-- Only one of these is needed.
		"nvim-telescope/telescope.nvim", -- optional
		"ibhagwan/fzf-lua", -- optional
		"echasnovski/mini.pick", -- optional
		"folke/snacks.nvim", -- optional
	},

	vim.keymap.set("n", "<leader>gg", "<cmd>Neogit<cr>", { desc = "Neogit" }),

	opts = {
		kind = "floating",
		-- Floating window style
		floating = {
			relative = "editor",
			width = 0.5,
			height = 0.7,
			style = "minimal",
			border = "rounded",
		},
		mappings = {
			commit_editor = {
				["<Esc>"] = "Close",
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
				["<Up>"] = "PrevMessage",
				["<Down>"] = "NextMessage",
				["<m-r>"] = "ResetMessage",
			},
			commit_editor_I = {
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
			},
			rebase_editor = {
				["p"] = "Pick",
				["r"] = "Reword",
				["e"] = "Edit",
				["s"] = "Squash",
				["f"] = "Fixup",
				["x"] = "Execute",
				["d"] = "Drop",
				["b"] = "Break",
				["q"] = "Close",
				["<cr>"] = "OpenCommit",
				["gk"] = "MoveUp",
				["gj"] = "MoveDown",
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
				["[c"] = "OpenOrScrollUp",
				["]c"] = "OpenOrScrollDown",
			},
			rebase_editor_I = {
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
			},
			finder = {
				["<cr>"] = "Select",
				["<c-c>"] = "Close",
				["<esc>"] = "Close",
				["<c-n>"] = "Next",
				["<c-p>"] = "Previous",
				["<down>"] = "Next",
				["<up>"] = "Previous",
				["<tab>"] = "InsertCompletion",
				["<c-y>"] = "CopySelection",
				["<space>"] = "MultiselectToggleNext",
				["<s-space>"] = "MultiselectTogglePrevious",
				["<c-j>"] = "NOP",
				["<ScrollWheelDown>"] = "ScrollWheelDown",
				["<ScrollWheelUp>"] = "ScrollWheelUp",
				["<ScrollWheelLeft>"] = "NOP",
				["<ScrollWheelRight>"] = "NOP",
				["<LeftMouse>"] = "MouseClick",
				["<2-LeftMouse>"] = "NOP",
			},
			-- Setting any of these to `false` will disable the mapping.
			popup = {
				["?"] = "HelpPopup",
				["A"] = "CherryPickPopup",
				["d"] = "DiffPopup",
				["M"] = "RemotePopup",
				["P"] = "PushPopup",
				["X"] = "ResetPopup",
				["Z"] = "StashPopup",
				["i"] = "IgnorePopup",
				["t"] = "TagPopup",
				["b"] = "BranchPopup",
				["B"] = "BisectPopup",
				["w"] = "WorktreePopup",
				["c"] = "CommitPopup",
				["f"] = "FetchPopup",
				["l"] = "LogPopup",
				["m"] = "MergePopup",
				["p"] = "PullPopup",
				["r"] = "RebasePopup",
				["v"] = "RevertPopup",
			},
			status = {
				["j"] = "MoveDown",
				["k"] = "MoveUp",
				["o"] = "OpenTree",
				["<leader>g"] = "Close",
				["<Esc>"] = "Close",
				["I"] = "InitRepo",
				["1"] = "Depth1",
				["2"] = "Depth2",
				["3"] = "Depth3",
				["4"] = "Depth4",
				["Q"] = "Command",
				["<cr>"] = "Toggle",
				["za"] = "Toggle",
				["zo"] = "OpenFold",
				["x"] = "Discard",
				["s"] = "Stage",
				["S"] = "StageUnstaged",
				["<c-s>"] = "StageAll",
				["u"] = "Unstage",
				["K"] = "Untrack",
				["U"] = "UnstageStaged",
				["y"] = "ShowRefs",
				["$"] = "CommandHistory",
				["Y"] = "YankSelected",
				["<c-r>"] = "RefreshBuffer",
				["gf"] = "GoToFile",
				["<s-cr>"] = "PeekFile",
				["<c-v>"] = "VSplitOpen",
				["<c-x>"] = "SplitOpen",
				["<c-t>"] = "TabOpen",
				["{"] = "GoToPreviousHunkHeader",
				["}"] = "GoToNextHunkHeader",
				["[c"] = "OpenOrScrollUp",
				["]c"] = "OpenOrScrollDown",
				["<c-k>"] = "PeekUp",
				["<c-j>"] = "PeekDown",
				["<c-n>"] = "NextSection",
				["<c-p>"] = "PreviousSection",
			},
		},
	},
}
