font_family      CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
enable_audio_bell no
font_size 12.0
window_padding_width 25
cursor_shape block
include theme.conf
confirm_os_window_close 0

map shift+up scroll_line_up
map shift+down scroll_line_down

map ctrl+backspace send_text all \x17

# Enable selection with shift + arrows
select_by_word_characters @-./_~?&=%+#

#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0

allow_remote_control yes

# Vim Scrollback
map ctrl+h pipe @screen_scrollback overlay nvim --clean -n - + -c 'set filetype=scrollback | set readonly | set clipboard=unnamedplus | nnoremap <C-q> :q!<CR>'


